### ISSUE TITLE
Automatically publish gem on release

### ISSUE THREAD

**Issue by clarkedb** [clarkedb/grift#11]
This happens manually right now with a rake command. We could use GitHub actions:

```yaml
name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish to Rubygems
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Publish to RubyGems
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
```
